<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0"
	xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
	xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
	xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
	xmlns:html="http://www.w3.org/TR/REC-html40">
	<xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
	<xsl:template match="/">
		<html xmlns="http://www.w3.org/1999/xhtml">
			<head>
				<title>XML Sitemap</title>
				<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
				<meta name="robots" content="noindex,follow"/>
				<style type="text/css">
					body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif; color: #545353; margin: 0; padding: 0; }
					a { color: #df3a01; text-decoration: none; }
					a:visited { color: #333333; }
					a:hover { text-decoration: underline; }
					#content { margin: 0 auto; padding: 30px 50px; max-width: 980px; }
					h1 { color: #000; font-size: 22px; margin: 0 0 6px; }
					p { font-size: 13px; }
					p.expl { margin: 5px 0 18px; color: #545353; }
					p.expl a { color: #df3a01; font-weight: bold; }
					table { border: none; border-collapse: collapse; width: 100%; }
					th { background-color: #4275f4; color: #fff; text-align: left; padding: 10px 15px; font-size: 14px; font-weight: 600; }
					td { padding: 10px 15px; font-size: 13px; }
					tr:nth-child(odd) td { background-color: #eee; }
					#footer { font-size: 12px; color: #999; text-align: center; padding: 20px 0; }
					#footer a { color: #999; }
				</style>
			</head>
			<body>
				<div id="content">
					<h1>XML Sitemap</h1>
					<p class="expl">
						Generated by <a href="https://rankmath.com/?utm_source=Sitemap&amp;utm_medium=XML+Sitemap" target="_blank" rel="noopener noreferrer">Rank Math SEO</a>, this is an XML Sitemap, meant for consumption by search engines.<br/>
						You can find more information about XML sitemaps on <a href="https://sitemaps.org" target="_blank" rel="noopener noreferrer">sitemaps.org</a>.
					</p>

					<xsl:if test="sitemap:sitemapindex">
						<p class="expl">
							This XML Sitemap Index file contains <xsl:value-of select="count(sitemap:sitemapindex/sitemap:sitemap)"/> sitemaps.
						</p>
						<table id="sitemap">
							<thead>
								<tr>
									<th width="75%">Sitemap</th>
									<th width="25%">Last Modified</th>
								</tr>
							</thead>
							<tbody>
								<xsl:for-each select="sitemap:sitemapindex/sitemap:sitemap">
									<tr>
										<td>
											<xsl:variable name="sitemapURL"><xsl:value-of select="sitemap:loc"/></xsl:variable>
											<a href="{$sitemapURL}"><xsl:value-of select="sitemap:loc"/></a>
										</td>
										<td><xsl:value-of select="sitemap:lastmod"/></td>
									</tr>
								</xsl:for-each>
							</tbody>
						</table>
					</xsl:if>

					<xsl:if test="sitemap:urlset">
						<p class="expl">
							This XML Sitemap contains <xsl:value-of select="count(sitemap:urlset/sitemap:url)"/> URLs.
						</p>
						<table id="sitemap">
							<thead>
								<tr>
									<th width="55%">URL</th>
									<th width="10%">Images</th>
									<th title="Priority" width="10%">Priority</th>
									<th width="10%">Change Freq.</th>
									<th width="15%">Last Modified</th>
								</tr>
							</thead>
							<tbody>
								<xsl:for-each select="sitemap:urlset/sitemap:url">
									<tr>
										<td>
											<xsl:variable name="itemURL"><xsl:value-of select="sitemap:loc"/></xsl:variable>
											<a href="{$itemURL}"><xsl:value-of select="sitemap:loc"/></a>
										</td>
										<td><xsl:value-of select="count(image:image)"/></td>
										<td><xsl:value-of select="concat(sitemap:priority*100,'%')"/></td>
										<td><xsl:value-of select="sitemap:changefreq"/></td>
										<td><xsl:value-of select="sitemap:lastmod"/></td>
									</tr>
								</xsl:for-each>
							</tbody>
						</table>
					</xsl:if>

					<div id="footer">
						<p>Generated with <a href="https://rankmath.com/?utm_source=Sitemap&amp;utm_medium=XML+Sitemap+Footer" target="_blank" rel="noopener noreferrer">Rank Math SEO</a> for BookMelbourneTaxi.com</p>
					</div>
				</div>
			</body>
		</html>
	</xsl:template>
</xsl:stylesheet>
